name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1

      - name: Run a multi-line script
        run: |
          ./format-check.sh
